### ISSUE TITLE
Logged in user data.

### ISSUE THREAD

**Issue by Indrajeetsing** [psvensson/node-red-contrib-firebase-admin#21]
Is there anyway I can know logged in user details?

**Comment by psvensson** [comment]
Currently these modules run by themselves and have no concept of a logged in user. They make use of a 'service account' user to access google storage, firestore, et.c. with full admin privileges.

There is, however, an admin API for user management that can verify the identity of a user given a JWT sent from a client, which is probably what you refer to; https://firebase.google.com/docs/auth/admin/verify-id-tokens#web

But I have not yet implemented a wrapper for this. But I think I could, if it's something you would like to have

**Comment by Indrajeetsing** [comment]
@psvensson thanks for response. Yes, if I pass JWT from client it will work.

 but if we have a wrapper, which gives us user management capabilities that would be great as we already have access to admin privileges.

**Comment by psvensson** [comment]
OK, then I will begin by wrapping this api for decoding and getting user info out of a JWT token; https://firebase.google.com/docs/auth/admin/verify-id-tokens#web.

I will have time over the weekend and will post here again when it's ready to test.

**Comment by psvensson** [comment]
Hello, I have now released a new version 1.1.24 which implements a new node called verify-idtoken which I hope will work as you would like. Let me know if you have any problems

**Comment by Indrajeetsing** [comment]
Thanks

**Comment by rtcimi** [comment]
I've manage to get it to work... after looking into source code and figuring out that **payload is not string as documentation is stating, but object with property "idtoken"**

**Comment by psvensson** [comment]
My apologies and thank you for finding the mistake. I'll correct the README immediately
