### ISSUE TITLE
Firestore query - wrong format in documentation

### ISSUE THREAD

**Issue by Josefernandez-dev** [psvensson/node-red-contrib-firebase-admin#23]
Hi,

I've run across an error in the documentation for the Firestore - query node.

Based on the documentation, this is the format:

![image](https://user-images.githubusercontent.com/71111157/102146143-98026680-3ebc-11eb-9611-24bec5f61121.png)

However, as marked in the picture there are two errors:

1) "queries" field appear twice.
2) in the "queries" array, every query must be inside [ ] and not { }. That's consistent with your implementation, and at the same time {"company", "==", "ACME"}, is not a correct syntaxes for js.

It would be great if you could update the documentation to avoid other people spend time looking for the error. Thanks.

Regards,

Jose

**Comment by psvensson** [comment]
My apologies for not fixing this until now, and thanks a lot for finding this. I must have been very tired when I wrote that :)
It should now be fixed in the latest version
