### ISSUE TITLE
Storage - write issue

### ISSUE THREAD

**Issue by abhishekranaji** [psvensson/node-red-contrib-firebase-admin#25]
On write buffer to storage i am getting error as below
"cloud storage write error: Error: The incoming JSON object does not contain a client_email field"
Whereas my credentials are correct and all configs on cloud is all correct

**Comment by psvensson** [comment]
it works for me when jsut testing now, but could it be that you have tried other firebase packages for node-red at the same time as this? The config node name collides with some of them, so check if this might be the case.

Otherwise, could you see if you could use a firebase or firestore node with the same config and verify that it works?

**Comment by abhishekranaji** [comment]
I have removed other firebase node for now
But it still creating same issue

**Comment by psvensson** [comment]
OK, and I understand that you have restarted node-red in between just in case it was needed. 

Hmm, have you tried to use your certificate with one of the firebase or firestore nodes in the same package as the storage node?  Just to see fi they are able to use your certificate?

**Comment by abhishekranaji** [comment]
Yes firebase rtdb is able to access it and working fine where at the same time storage causing issues

**Comment by psvensson** [comment]
OK, and is it still the same error I assume. That is very strange. All service account certificates should have an client_email field. I'm wondering if the problem could be something else. Hmm, are you abel to uplaod files using another tool, like directly from the web console fro storage or from google sdk cli tool?

**Comment by abhishekranaji** [comment]
Wait it have strange behavior that for sometime after restart machine it works and  after sometime it again start creating the error.
Can you give me hint where i have to check this

**Comment by psvensson** [comment]
Unfortunately not, as I can not reproduce your problem. One thing you could try, is to install node-red on another machine and test if that makes any difference. I have not seen before that it sometimes works and sometimes not, I'm afraid.

**Comment by abhishekranaji** [comment]
I got the problem. Thanks for the help. The other firebase node red package was not removed properly. That's why this happened.

**Comment by psvensson** [comment]
Thank you so much for reporting this back!
