### ISSUE TITLE
firestore on - path is not defined

### ISSUE THREAD

**Issue by yizenlim** [psvensson/node-red-contrib-firebase-admin#32]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/29494103/171264600-4e54736a-2fba-46c5-b118-8edb9f0dc5de.png">

Firestore-on.js 

i think this requires a param (Path) , node fails at path is not defined.

**Comment by psvensson** [comment]
Thank you, I have fixed this (and another bug I found) in firestore-on. Please see if the new version 1.1.30 works for you
